[project]
name = "adstack-contracts"
description = "Smart contracts for the AdStack decentralized advertising platform"
authors = ["Gbolahan Akande <geakande@gmail.com>"]
telemetry = true
cache_dir = "./.cache"

[contracts.user-profiles]
path = "contracts/user-profiles.clar"
clarity_version = 4
epoch = '3.0'

[contracts.promo-manager]
path = "contracts/promo-manager.clar"
clarity_version = 4
epoch = '3.0'
depends_on = ["user-profiles"]

[contracts.stats-tracker]
path = "contracts/stats-tracker.clar"
clarity_version = 4
epoch = '3.0'
depends_on = ["promo-manager"]

[contracts.vote-handler]
path = "contracts/vote-handler.clar"
clarity_version = 4
epoch = '3.0'

[contracts.funds-keeper]
path = "contracts/funds-keeper.clar"
clarity_version = 4
epoch = '3.0'
depends_on = ["promo-manager"]

[contracts.cash-distributor]
path = "contracts/cash-distributor.clar"
clarity_version = 4
epoch = '3.0'
depends_on = ["funds-keeper"]

[contracts.threat-detector]
path = "contracts/threat-detector.clar"
clarity_version = 4
epoch = '3.0'
depends_on = ["stats-tracker"]

[contracts.audience-selector]
path = "contracts/audience-selector.clar"
clarity_version = 4
epoch = '3.0'
depends_on = ["user-profiles"]

[contracts.partner-hub]
path = "contracts/partner-hub.clar"
clarity_version = 4
epoch = '3.0'

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
