module.exports = {
  apps: [
    {
      name: "adstack-backend",
      script: "dist/server.js",
      cwd: "./backend",
      instances: "max",
      exec_mode: "cluster",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "adstack-websocket",
      script: "dist/index.js",
      cwd: "./websocket-server",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3002,
      },
      error_file: "./logs/websocket-error.log",
      out_file: "./logs/websocket-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "adstack-bridge-relayer",
      script: "dist/index.js",
      cwd: "./bridge-relayer",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3003,
      },
      error_file: "./logs/bridge-error.log",
      out_file: "./logs/bridge-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
